### ISSUE TITLE
Can't add comment on task card modal.

### ISSUE THREAD

**Issue by GoDotDotDot** [JordanKnott/taskcafe#110]
**Describe the bug**
I can't add link comment on task card, for example the comment content is: https://github.com/JordanKnott/taskcafe/issues/new?assignees=&labels=&template=bug_report.md&title=

and the page will be crashed.
**Expected behavior**
What did you expect to happen?

**Screenshots / Live demo link**

**Additional context**

Please send the Taskcafe web service logs if applicable.

**Comment by JordanKnott** [comment]
This should be fixed in the latest (`0.3.2`) version.
