### ISSUE TITLE
Putting URL into a card comment crashes page

### ISSUE THREAD

**Issue by Aesir** [JordanKnott/taskcafe#111]
**Describe the bug**
Pasting a URL into a comment in a card causes the page to turn white and become unavailable. Afterward, opening that card again causes the crash as well.

**Expected behavior**
A comment is created with a link as the text. Bonus points if it's clickable.

**Screenshots / Live demo link**
https://user-images.githubusercontent.com/447759/110708082-0d758e80-81af-11eb-86d8-2286cfaab01a.mp4

**Comment by santosh** [comment]
I confirm the same problem.

**Comment by JordanKnott** [comment]
This should be fixed in the latest (`0.3.2`) version.
