### ISSUE TITLE
Creating new users via /admin doesn't make them active

### ISSUE THREAD

**Issue by heroje** [JordanKnott/taskcafe#118]
... and I can't figure out a way to make them.
I'm running this application via Docker.
I created a Member type user on the /admin page, tried resetting the password via Docker terminal (./taskcafe reset-password username password_wo_spaces), and it didn't do anything. I also tried to add this account to a project - nothing.
Whenever I try to login with the user, I get the same message in log:
web_1 | time="08-04-2021 21:17:18" level=warning msg="attempt to login with inactive user" username=username

**Comment by JordanKnott** [comment]
This should be fixed in the latest (`0.3.2`) version.
