### ISSUE TITLE
graphql with ngnix

### ISSUE THREAD

**Issue by MohamedElashri** [JordanKnott/taskcafe#119]
**Describe the bug**
I upgraded to the latest version today, I setup my domains on my vps via ngnix proxy manager. When I redirect domain.tld:333 to something like tasks.domain.tld everything cannot load and project dissapears. Tried this on Chrome, Edge,Firefox and Safari and it gives the same. When I inspect it gives me that it cannot load the graphql 

**Expected behavior**
Everything should be accessed the same like when accessing through port.
**Screenshots / Live demo link**
![Screenshot](https://i.imgur.com/UTEyaL0.png)

**Additional context**

**Inspection logs**
This is a sample of the repeated logs

```
[Network error]: ServerParseError: JSON.parse: unexpected character at line 1 column 1 of the JSON data index.tsx:103:12
[Network error]: ServerParseError: JSON.parse: unexpected character at line 1 column 1 of the JSON data index.tsx:150:16
XHRPOSThttps://tasks.domain.tld/graphql
[HTTP/2 401 Unauthorized 136ms]

[Network error]: ServerParseError: JSON.parse: unexpected character at line 1 column 1 of the JSON data index.tsx:103:12
[Network error]: ServerParseError: JSON.parse: unexpected character at line 1 column 1 of the JSON data index.tsx:150:16
XHRPOSThttps://tasks.domain.tld/graphql
[HTTP/2 401 Unauthorized 132ms]

```

**Comment by JordanKnott** [comment]
My own personal instance of Taskcafe uses Nginx as a reverse proxy and it works fine with the 0.3.2 release.

Can you post the taskcafe server logs and your nginx config?

**Comment by MohamedElashri** [comment]
> My own personal instance of Taskcafe uses Nginx as a reverse proxy and it works fine with the 0.3.2 release.
> 
> Can you post the taskcafe server logs and your nginx config?

I did some debugging, and it seems the problem was that I put taskcafe beyond some access auth that keep promoting to enter auth in background even after you successfully do it.  I'm not sure if it still something important or not, but it is not a big problem since taskcafe have internal auth system anyway. 
Thank you for your product and support.
