### ISSUE TITLE
Closing a card with Esc when the label dialogue is open and then choosing to create a new label produces a blank screen

### ISSUE THREAD

**Issue by almereyda** [JordanKnott/taskcafe#120]
**Describe the bug**

When opening a card on a board, and considering to add a label, and then choosing to close the modal dialogue with Esc, it is not the *Add label* dialogue that is closed, but the detail view of the card. The *Add label* dialogue will continue to be displayed, until one clicks outside of it, or on its X. When clicking on *Create label* in this orphaned dialogue, the whole screen will turn to blank, and a page reload is required.

**Expected behavior**

- Pressing Esc closes the upmost dialgoue, and not the one below it.

**Screenshots / Live demo link**

![Screenshot_2021-05-07 Überblick Taskcafé](https://user-images.githubusercontent.com/1645308/117489278-b7825480-af6d-11eb-9896-577ea50c90b8.png)

![Screenshot_2021-05-07 Überblick Taskcafé(1)](https://user-images.githubusercontent.com/1645308/117489277-b7825480-af6d-11eb-901d-653b2fcc5f69.png)

![Screenshot_2021-05-07 Überblick Taskcafé(2)](https://user-images.githubusercontent.com/1645308/117489276-b6e9be00-af6d-11eb-92f0-025c5406481e.png)

![Screenshot_2021-05-07 Überblick Taskcafé(3)](https://user-images.githubusercontent.com/1645308/117489274-b6e9be00-af6d-11eb-8e4c-ec5bc92d70a6.png)

![Screenshot_2021-05-07 Überblick Taskcafé(4)](https://user-images.githubusercontent.com/1645308/117489271-b6512780-af6d-11eb-8f8d-a6f077424ea4.png)

**Additional context**
This happened with `master`'s HEAD pointing to `5a9a66effe2eea05ad1bef276e90b346c80e18f9`

Please send the Taskcafe web service logs if applicable.

This is purely client side. No additional webserver logs are displayed.

**Comment by JordanKnott** [comment]
This has been fixed in the latest commit. Any open popups should now be closed when closing the task details modal.
