### ISSUE TITLE
react-scripts fail to build

### ISSUE THREAD

**Issue by ThatIsAPseudo** [JordanKnott/taskcafe#124]
**Describe the bug**
The build fails at step
```
yarn run v1.22.11
$ react-scripts build
```

**Screenshots / Live demo link**
Here is the output of the `install` and `build` commands : https://bin.snopyta.org/?3f2a8cc989456c6b#BAutMSd9U9mjq1sx5E4HKaXbnDd1dNRkx9NFtg2ekr5n

**Comment by JordanKnott** [comment]
This seems like an issue that was happening in older versions. Try updating to `0.3.6`

**Comment by ThatIsAPseudo** [comment]
Indeed, building succeeds now. Thanks !
