### ISSUE TITLE
Initial Install does not bring up installation screen

### ISSUE THREAD

**Issue by Lukejvv** [JordanKnott/taskcafe#130]
After installing via Cloning the repo, and running with docker-compose the initial load of the webpage at localhost:3333 loads localhost:3333/login rather than the expected installation screen.

**Comment by JadeVane** [comment]
Same here

**Comment by AlbertoGM97** [comment]
Same. I've solved it pointing to a previous docker image in the compose file (taskcafe/taskcafe:0.3.0). That way it allows to go through the install screen and create a user. Then modifying the compose again to point to the latest release (taskcafe/taskcafe:latest) and composing up. That way you'll be able to log in with the newly created user.

**Comment by mashirozx** [comment]
> Same. I've solved it pointing to a previous docker image in the compose file (taskcafe/taskcafe:0.3.0). That way it allows to go through the install screen and create a user. Then modifying the compose again to point to the latest release (taskcafe/taskcafe:latest) and composing up. You should be able to log in with the newly created user.

So, seems a bug on new version

**Comment by JadeVane** [comment]
Solved. Just visit http://localhost:3333/register and add a user by yourself.

**Comment by JordanKnott** [comment]
A redirect has been added in the latest commit

**Comment by mithlajkn** [comment]
I am also facing the same issue with the latest code.

**Comment by mabushey** [comment]
Same here, but manually changing `/login` to `/register` works
