### ISSUE TITLE
Should I Be Concerned?

### ISSUE THREAD

**Issue by AiFxApp** [JordanKnott/taskcafe#154]
**Describe the bug**

`go run cmd/mage/main.go install`

go: downloading github.com/magefile/mage v1.11.0
yarn install v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["@apollo/client@latest"] is trying to unpack in the same destination "C:\\Users\\aifxapp\\AppData\\Local\\Yarn\\Cache\\v6\\npm-@apollo-client-3.4.16-67090d5655aa843fa64d26f1913315e384a5fa0f-integrity\\node_modules\\@apollo\\client" as pattern ["@apollo/client@^3.3.16"]. This could result in non-deterministic behavior, skipping.
[3/4] Linking dependencies...
warning " > @apollo/react-common@3.1.4" has incorrect peer dependency "@types/react@^16.8.0".
warning " > @apollo/react-common@3.1.4" has incorrect peer dependency "graphql@^14.3.1".
warning " > @apollo/react-common@3.1.4" has incorrect peer dependency "react@^16.8.0".warning "@taskcafe/rich-markdown-editor > prosemirror-utils@0.9.6" has incorrect peer dependency "prosemirror-tables@^0.9.1".
warning " > react-autosize-textarea@7.1.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-autosize-textarea@7.1.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > styled-components@5.3.3" has unmet peer dependency "react-is@>= 16.8.0".
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
Done in 186.78s.

**Comment by JordanKnott** [comment]
No
