### ISSUE TITLE
Chrome cannot be dragged , but edge can。

### ISSUE THREAD

**Issue by lxz8798** [JordanKnott/taskcafe#161]
Chrome cannot be dragged , but edge can。
My chrome version 103.0.5060.134（64 位）

**Comment by JordanKnott** [comment]
Which version of taskcafe are you using?

**Comment by GwynethLlewelyn** [comment]
Hm. I have tested both on the latest Brave and Edge (both are Chromium-based), as well as on Safari and Firefox — all the latest versions as of January 2023 — and the dragging feature consistently works across all of them, at least under macOS Big Sur 11.7.3. Taskcafé is commit 998db2a5da497a7902198a728ddc040fcacbacd6 (schema migration 65).

**Comment by JordanKnott** [comment]
Unable to replicate on my end
