### ISSUE TITLE
Cannot add items after first

### ISSUE THREAD

**Issue by FrozenSource** [JordanKnott/taskcafe#39]
At master-commit https://github.com/JordanKnott/taskcafe/commit/22e4669c3434e60bffec9c71bfe90b26765d8506
After having created a first item and label. I am unable to create new items.

**Comment by JordanKnott** [comment]
Hmm, still not able to replicate the issue on my end.

Were all 7 lists in the same project (this is what I did) or across both projects?

**Comment by FrozenSource** [comment]
[log.txt](https://github.com/JordanKnott/taskcafe/files/5121679/log.txt)
I removed everything db, etc. and pulled again. Using the same steps but with one project and team. I got the same results.
I have a feeling it has to do with the labels but am not sure.

**Comment by jonwv** [comment]
Not sure if it helps, but for me it only fails to create if I click the button "add card". Pressing enter instead will still successfully create items.

**Comment by FrozenSource** [comment]
It seems that in the latest version the problem is fixed...... So I guess that solves it?

**Comment by JordanKnott** [comment]
Yay? I'm still not sure what would have been causing this
