### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by HiNsKeY** [JordanKnott/taskcafe#45]
It would be great if the application set up the database as part of the initial setup. This would mean the extra migration docker-compose would not be required.

**Comment by JordanKnott** [comment]
This is actually a feature that is already been added. 

You can pass `--migrate` to the `web` command & migrations will automatically be ran. 

The `docker-compose.yml` does this already by passing the env variable `TASKCAFE_MIGRATE`, which does the same thing.
