### ISSUE TITLE
Feature: Authenticate via "Remote User" header

### ISSUE THREAD

**Issue by aroberts** [JordanKnott/taskcafe#49]
In the case that access to taskcafe is through a reverse proxy, it would be great to support "Remote-User" login - the reverse proxy performs its own authentication, and adds a header with the user that the request belongs to. Taskcafe should consume this header and treat it as a successful login, if the user exists.

This is related to #20, but a much simpler implementation, and still very broadly applicable.

**Comment by JordanKnott** [comment]
For those interested in working on this issue:

This behavior should be allowed only if the config option `server.remote_user_header` is set to `true`.

Taskcafe uses [Viper](https://github.com/spf13/viper/) to handle configuration.

Relevant files

- `internal/commands/web.go`
- `internal/route/middleware.go`


Please take a look at the [contributing guide](https://github.com/JordanKnott/taskcafe/blob/master/CONTRIBUTING.md) as well as the [developers guide](https://github.com/JordanKnott/taskcafe/wiki/Developers-Guide) for an idea on how the project is structured.

**Comment by MistaTwista** [comment]
Looks like I can take it

**Comment by MistaTwista** [comment]
@JordanKnott few questions, just to make sure I'm understand well what do I need to do in this case.

As I see, in auth middleware you check Authorization header with JWT, and there are authorizations, user data and so on. So if I right we need to make changes not in a middleware that check JWT token, but in login procedure that gives us this token.

What do you think if my changes will be at `internal/route/auth.go:160 (func (h *TaskcafeHandler) LoginHandler(w http.ResponseWriter, r *http.Request))` somewhere here. I've planned something like:

1. If `server.remote_user_header` is set to true
2. Take username from `Remote-User` header
3. Get user from repo
4. If user exists - skip password checking and make a token

It's simple, but we still need to understand how to do user registration. Taskcafe somehow needs to create user in it's DB.

What do you think?

**Comment by aroberts** [comment]
the "create user" step could certainly be broken out into its own system. Third party auth generally implies third party user store (e.g. LDAP, AD), and that means different things based on app capabilities and so on. The trouble with auto-creating users is everything beyond the username you're getting from the header: Do these new users belong to a team? which team? What are the permissions of the created user? The list goes on.

I would say that all the answers to the above are in the purview of either a user sync module or a pluggable user backend, and needn't be addressed here. If there is no user found in step 3, I would silently ignore the header.

**Comment by MistaTwista** [comment]
I don't mean user auto creation, for sure :) i thought about some API for third party service, that can creates a user at a Taskcafe. Better way is completely extract user and his authentications and making something like pluggable system, but it need more changes and refactoring.

@aroberts do you plan to add users in DB by some of your services?

**Comment by aroberts** [comment]
It’s not an immediate need, but it would be nice to have. I add users rarely, and I am centralized around ldap.

**Comment by JordanKnott** [comment]
Hmm -  I think I underestimated the complexity of this feature.

I'm not really sure how user creation would work, as I imagine it would really depend on what software is being used @aroberts Is there a particular software / setup that you're wanting to use so that I have a good reference on how it would work for a user?

**Comment by aroberts** [comment]
@JordanKnott It's my intention to leave user creation out of scope for this ticket for exactly that reason - there are tons of questions surrounding it without great answers. Additionally, adding a user is a rarity for me compared to login through my SSO. What I was getting at above is, it's no trouble to manually create users in order to make SSO login work.

**Comment by JordanKnott** [comment]
@MistaTwista Instead of using the `/auth/login` endpoint, we create a different `/auth/sso` endpoint 
that accepts the `Remote-User` header and returns the refresh + access tokens. 

Then we could add a new button to the login for SSO login that just calls the endpoint.

Thoughts?

**Comment by aroberts** [comment]
I'm not sure how that would work.. I've never implemented this in a SPA, but I feel like it's something that's occurring when `index.html` loads, not part of the javascript.

The flow that's implied (to me) is:
-> user hits my taskcafe subdomain
-> reverse proxy fields the request, challenges for auth (sso)
-> auth success, reverse proxy forwards request to underlying taskcafe backend, adding a header with the auth'd username 
-> taskcafe receives header, and logs requested user in before delivering index.html and starting whatever javascript

There shouldn't need to be a button (because what protocol would `/auth/sso` use?) or anything like that - other than acting on the header, there should be very little code needed on the backend, and zero on the frontend I think.

**Comment by JordanKnott** [comment]
Maybe the `Remote-User` check can just be added to the refresh token handler?

That might be the best way since it would work kinda like how you described without requiring much changes.

**Comment by aroberts** [comment]
That seems like it might work - I'll try to take a read tomorrow and see if I see any issues with that spot.
