### ISSUE TITLE
Unraid Install

### ISSUE THREAD

**Issue by Bloham** [JordanKnott/taskcafe#50]
Hi, I need some help to get taskcafe to work on my unraid server. Maybe someone figured it out already, as there is a community application for it already. I guess my main problem is to use Postgres (11) where I have no idea how to create a new user and database for taskcafe. Maybe someone can help ^^ ?

**Comment by JordanKnott** [comment]
Closed due to community member written instructions - https://github.com/JordanKnott/taskcafe/wiki/Unraid-Install-(Community)
