### ISSUE TITLE
Failed to upload an avatar picture

### ISSUE THREAD

**Issue by mzch** [JordanKnott/taskcafe#55]
**Describe the bug**
Failed to upload an avatar picture. TaskCafe said:

```
9月 07 01:28:43 n24 taskcafe[6683]: time="07-09-2020 01:28:43" level=info msg="preparing to upload file"
9月 07 01:28:43 n24 taskcafe[6683]: time="07-09-2020 01:28:43" level=error msg="not a valid uuid"
```
What's wrong?

**Expected behavior**
Change my avatar picture.

**Screenshots / Live demo link**
None.

**Additional context**
None.

**Comment by mzch** [comment]
Also, I tried to change my profile, i.e. bio but failed.

<img width="1497" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/92367730-c50ee280-f131-11ea-9939-d8664657ae88.png">

Any idea?

**Comment by shmuelpro** [comment]
Whats the name of the file you are trying to upload? does it have japanese in it?

**Comment by JordanKnott** [comment]
This has been fixed.

The issue was that I had the wrong context key for getting the UserID.
