### ISSUE TITLE
User icon glitch

### ISSUE THREAD

**Issue by mzch** [JordanKnott/taskcafe#61]
**Describe the bug**
On the top of right no user icon is shown. Built from the latest source (61cd376bfd0e9272b9c0cfd3497dbf163728e35f).

**Expected behavior**
Uploaded avatar is shown.

**Screenshots / Live demo link**
![ScreenShot](https://user-images.githubusercontent.com/621178/92990367-f400cc00-f516-11ea-946e-942c045e397f.png)

**Additional context**
None.

**Comment by MohamedElashri** [comment]
I cannot upload an avatar at all if this can be a related problem.

**Comment by JordanKnott** [comment]
If you reload, it should fix the issue. 

And the issue is most likely related - I'll be looking into this next chance I get!

**Comment by mzch** [comment]
When reloading any number of times, no icon is shown at all.

**Comment by JordanKnott** [comment]
Try with commit e2ef8a1

**Comment by mzch** [comment]
Unfortunately this issue still remains.

**Comment by mzch** [comment]
-log
```
Sep 12 01:34:59 n24 taskcafe[27902]: time="12-09-2020 01:34:59" level=info msg="running auto schema migrations"
Sep 12 01:34:59 n24 taskcafe[27902]: time="12-09-2020 01:34:59" level=info msg="starting server" url="127.0.0.1:3333"
Sep 12 01:35:24 n24 taskcafe[27902]: time="12-09-2020 01:35:24" level=info msg="fetching notifications" userID=c463affc-dbed-47d7-b408-565d9a350a70
Sep 12 01:35:24 n24 taskcafe[27902]: time="12-09-2020 01:35:24" level=info msg="fetching projects" userID=c463affc-dbed-47d7-b408-565d9a350a70
Sep 12 01:35:24 n24 taskcafe[27902]: time="12-09-2020 01:35:24" level=info msg="showing all projects for admin"
```

**Comment by JordanKnott** [comment]
Hmm - is there any error in your browser console? (ctrl + shift + i)

**Comment by mzch** [comment]
I don't find any errors in my chrome console.

**Comment by JordanKnott** [comment]
Then I'm not sure what could be causing it. I'll test some more on my end when I get a chance but so far I haven't been able to replicate this on my end

**Comment by mzch** [comment]
When removing an uploaded photo, an avatar is shown correctly.

![ScreenShot](https://user-images.githubusercontent.com/621178/92992073-02ed7b80-f523-11ea-818e-321458803362.png)

**Comment by JordanKnott** [comment]
And if you re upload the image, it still doesn't work? 
What's the images file size and name?

**Comment by mzch** [comment]
Yes, it doesn't work. The image size is 240 px x 240 px (102KB), 'Face of Myself.png'

**Comment by JordanKnott** [comment]
Hmm maybe it's the spaces? I'll test that when I get a chance

**Comment by mzch** [comment]
That's it! Uploading an image whose name doesn't include any spaces shows my avatar correctly.

**Comment by JordanKnott** [comment]
Spaces should now be fine in avatar image filenames (as well as any special characters)

**Comment by mzch** [comment]
Fine! Thank you! 👍
