### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by capriciousduck** [JordanKnott/taskcafe#63]
When can I host the docker version for free instead on localhost? Any free alternatives?

**Comment by JordanKnott** [comment]
Im unsure of any free hosts that would allow you to run arbitrary docker imagines or binaries - and if there are, I'm not sure if I would trust them to be honest.

If you're able to, your best bet for hosting would be something like Digital Ocean - that's where I host my private instance.

**Comment by tionis** [comment]
@capriciousduck If you're European I can also recommend Hetzner. Very cheap VMs that are reasonably powerful. Then of course you have to maintain them yourself.

Easier albeit more expensive if the free plan is not enough for you would be heroku. But you would first have find out how to run this application there.

**Comment by capriciousduck** [comment]
@tionis How do I change the listening port of taskcafe? Heroku assigns a random port. I have to use $PORT in taskcafe config to run on heroku.

**Comment by tionis** [comment]
@capriciousduck As far as I know this would require a code change in the server code.

**Comment by JordanKnott** [comment]
@capriciousduck you should be able to change the listening port of the server using the env variable `TASKCAFE_SERVER_HOSTNAME` and set it to something like `0.0.0.0:$PORT`

**Comment by obbardc** [comment]
I'd recommend using docker-compose on digital ocean or similar. The port can be changed in the docker-compose configuration.

**Comment by capriciousduck** [comment]
@obbardc Yeah. I signed up on [Webdock.io](https://webdock.io). Taskcafe is running smooth on my server.
