### ISSUE TITLE
Can taskcafe support LDAP auth ?

### ISSUE THREAD

**Issue by exqlnet** [JordanKnott/taskcafe#69]
**Is your feature request related to a problem? Please describe.**
It's difficult to integrate LDAP authentication or others. So I can not use my own account system.

**Describe the solution you'd like**
Support configure LDAP authentication

**Describe alternatives you've considered**

**Additional context**

**Comment by BeGj** [comment]
No. Better solution is to support openid and setup Keycloak on your backend which supports LDAP to openid. Simply explained.

**Comment by JordanKnott** [comment]
Thanks for the suggestion, however it's very unlikely Taskcafe will support LDAP - the only planned external authentication method is through OpenID.
