### ISSUE TITLE
Feature: Sort by complete

### ISSUE THREAD

**Issue by JordanKnott** [JordanKnott/taskcafe#70]
Add "Complete" sort option that would sort tasks by their complete state.

Complete tasks would be at the top of the list, then the incomplete tasks.

Relevant files

- `frontend/src/shared/utils/sorting.ts`
- `frontend/src/Projects/Project/Board/SortPopup.tsx`
- `frontend/src/Projects/Project/Board/index.tsx`

![taskcafe_complete_sort](https://user-images.githubusercontent.com/11680844/94773346-30d71a80-0381-11eb-8472-e3521d606568.png)

Please take a look at the [developers guide](https://github.com/JordanKnott/taskcafe/wiki/Developers-Guide) for an idea on how the project is structured.

**Comment by cainwatson** [comment]
Hi @JordanKnott, I can take this on!

**Comment by JordanKnott** [comment]
@cainwatson Sounds good!

**Comment by falguni-k** [comment]
I'll do it.

**Comment by JordanKnott** [comment]
Seems I already implemented the logic for this, just never added the button to the popup... Just makes it an easier first issue I guess!

**Comment by cainwatson** [comment]
@JordanKnott Yeah just noticed that. I just submitted a PR

**Comment by JordanKnott** [comment]
PR has been merged!
