### ISSUE TITLE
Feature: Add reset user password CLI command

### ISSUE THREAD

**Issue by JordanKnott** [JordanKnott/taskcafe#71]
Implement `reset-password` command that updates a user's password given a `username` and `password` argument.

Example usage
```
$ taskcafe reset-password jordan i_am_sneaky
Updated user "jordan" password
```

Relevant files 
- `internal/commands/commands.go`
- `internal/commands/token.go` - this is a good example of how a command can be implemented
- `internal/db/user_accounts.sql.go` - implementation of user DB access methods
- `internal/db/query/user_accounts.sql` - SQL query file that is turned into the above implementation 

Please take a look at the [developers guide](https://github.com/JordanKnott/taskcafe/wiki/Developers-Guide) for an idea on how the project is structured.

**Comment by IJustDev** [comment]
Would love to work on this. Is it still free?

**Comment by JordanKnott** [comment]
@IJustDev It is still available

**Comment by IJustDev** [comment]
I've gone through the files you have mentioned. Unfortunately I don't see an example that explains how to create a query from within a cli command.

- [ ] Do I need to connect to the database myself?
- [ ] How to query the database?
- [ ] Shall we add this to the developer documentation? Would be a huge help.

**Comment by vishals11** [comment]
Hi @JordanKnott , I have gone through the issue and looked into the code as well. My approach would be -
1. I will write a handler for reset user password under route package.
2 To update the existing password after resetting the old one, I will write a query in user_acc_seq.go file under db package.
3. I will test the API on the local machine and will make other changes if needed.

Please let me know if this ticket is still open. I would like to work on this.

**Comment by JordanKnott** [comment]
@IJustDev 

> Do I need to connect to the database myself?

Yes, You can see an example on connecting to the database in `internal/commands/web.go` line 35-40.

>  How to query the database?

With the connection you can create the repository object which has various methods for interacting with the database. (the methods are generated by `sqlc` from the query files in `internal/db/query`).

For example, to set the user password with you can do

```
repository.SetUserPassword(ctx, db.SetUserPasswordParams{UserID: userID, PasswordHash: passwordHash})
```

Passwords are hashed using `bcrypt`, an example on how to do so can be found in `internal/graph/schema.resolver.go` line 767

Hopefully the above helps!

> Shall we add this to the developer documentation? Would be a huge help.

I've working on the developer guide as I have time, I'll try and add a section on database access.

@vishals11 It is easier to just reset the password using a direct database connection than trying to use a graphql endpoint. Unless @IJustDev no longer wishes to work on this, then the issue is currently claimed

**Comment by IJustDev** [comment]
I will try to include it tomorrow. If I don't manage within 24 hours I would love to see you working on it @vishals11 if you still want to.

**Comment by IJustDev** [comment]
So I've implemented it and will create a pr in a short time. Let me know what you think.
