### ISSUE TITLE
Refactor: replace moment.js with day.js

### ISSUE THREAD

**Issue by JordanKnott** [JordanKnott/taskcafe#74]
The frontend client uses [Moment.js](https://momentjs.com/docs/#/-project-status/) for pretty much anything date related however it now considered a __legacy__ project and advises users to migrate to a new library. 

[Day.js](https://github.com/iamkun/dayjs) seems like the best library with a good API.

All instances of moment.js should be replaced with day.js calls while keeping the same functionality.

__For hacktoberfest users__

This issue touches many different places within the frontend code, so I would only recommend this to users with a good idea on how to use React & Typescript.

**Comment by nurseiit** [comment]
Looks like `moment` is used in only ~7 files. I can work on this refactor.
