### ISSUE TITLE
Clicking 'Add Card' Does Not Add Card

### ISSUE THREAD

**Issue by focalfury** [JordanKnott/taskcafe#76]
**Clicking the "Add Card after typing or pasting text does not add the card**
After clicking on **+Add another card** and either pasting text or typing text in and clicking the **Add Card** purple icon below the entered text the card is not added to the list.  It appears that only hitting _Enter_ saves the new card to the list

**Expected behavior**
A new card would be added

**Screenshots / Live demo link**
https://imgur.com/a/GKECzjL

**Additional context**
I did include in the video that clicking outside of the window instead of clicking Add Card also doesn't work.  This would be more of a Quality of Life request/addition
This was recorded on Firefox 81.0 incognito window
It also is not working in Chrome 85.0.4183.121

Please send the Taskcafe web service logs if applicable.

**Comment by JordanKnott** [comment]
This has been fixed in the nightly version of taskcafe.
