### ISSUE TITLE
CalDAV Import/Export Synchronization

### ISSUE THREAD

**Issue by yairark** [JordanKnott/taskcafe#80]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
Currently use CalDAV to store tasks from other apps (i.e, Tasks.org,etc) however I don't have a front-end to manage tasks on the web-browser via the kanban-like functionality that taskcafe currently offers. Excited to see how the roadmap progresses and wanted to know if CalDAV synchronization and import/export to CALDAV compatible systems is currently on the horizon.

**Describe the solution you'd like**
The ability to import/export and/or sync to CALDAV tasks from NextCloud or other CalDAV-compatible systems manageable through the taskcafe front-end

**Describe alternatives you've considered**
I was thinking about manually exporting tasks from CalDAV and then fitting them to taskcafe task structures but not sure what the final data model for taskcafe would look like in the future
. 
**Additional context**
Using Tasks.org to manage task tracking for now and would like to see if this feature would be something to be integrated into the roadmap moving forward.

**Comment by almereyda** [comment]
This is a very neat idea to leverage the often underused CalDAV tasks and to build a decoupled Kanban frontend for them.

Please note that Nextcloud also has the Cards App, which integrates with the rest of the system. Eventually that could also be a good place to ask for implementing this feature?
