### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by liliang8858** [JordanKnott/taskcafe#84]
**Describe the bug**
http://127.0.0.1:3333/
![image](https://user-images.githubusercontent.com/38367404/95744619-30fee080-0cc6-11eb-9c7b-53202384cbda.png)

**Expected behavior**
```
taskcafe web --config ../conf/app.toml
```

**Comment by liliang8858** [comment]
```
D:\app\taskcafe\dist>taskcafe -v
Version: dev
Commit: none
Built: unknown
```

**Comment by JordanKnott** [comment]
Can you re-run the build step `go run cmd/mage/main.go build` and post the output?

**Comment by liliang8858** [comment]
I found the reason, the database was used incorrectly and mysql was used instead
