### ISSUE TITLE
[Feature request] Docker support for ARM processors?

### ISSUE THREAD

**Issue by ParmuSingh** [JordanKnott/taskcafe#88]
I have had problems running docker instance on my raspberry pi 4. As it turns out the image is not for ARM architecture, which a rpi uses.

After going through some pain I was able to install from source and compile a binary for my rpi 

So the good news is that taskcafe does work on ARM.

The feature request is to have a docker image available for ARM architecture, as it'll help in easy deployment on rpi.

**Comment by JordanKnott** [comment]
If I am able to do it on my machine without actually having an ARM chip, then sure I can provide ARM images.

**Comment by ParmuSingh** [comment]
Anyway I can help with that? I compiled on a raspberry pi. If I share my binary would that help? I just don't know how to dockerize it.

**Comment by Fernthedev** [comment]
My best guess would be using an arm64 image of Ubuntu or some lightweight OS and run the same compile process for any Docker image (which I'm assuming is compiling the binary, and then building the image)
Of course, you'll have to make sure the arm version of the image uses everything ARM such as the OS and the GoLang tools for compiling (I'm assuming).

**Comment by JordanKnott** [comment]
I looked into it and from what I've found the best for me to release arm64 images (since I don't have an ARM based computer) is to use the `buildx` tool. Unfortunately it seems kind of annoying to install, but I'll try building the `0.4.0` release with it.
