### ISSUE TITLE
Unable to mark task as complete even for admin user

### ISSUE THREAD

**Issue by mrcodekiddie** [JordanKnott/taskcafe#90]
Unable to mark task as complete even for admin user

**Comment by JordanKnott** [comment]
Please send the server logs as well as any Dev tools console errors please.

**Comment by mrcodekiddie** [comment]
no error logs, fresh server , docker installation

**Comment by JordanKnott** [comment]
Can you reliably reproduce the issue on a new fresh install and if so what are the steps?
