### ISSUE TITLE
Please use Discussions for questions and feature requests

### ISSUE THREAD

**Issue by JordanKnott** [JordanKnott/taskcafe#93]
Now that the new Discussions feature is publicly available, I'd like to use it to separate bugs and feature requests. Bugs should still be added to the issue tracker, while questions & feature request should now be added to GitHub Discussions.

## Summary
- Issues will strictly be for Bug Reports
  - Issues that are not bugs will be closed and redirected to Discussions
- Discussions is for questions, feature requests, show and tell, TIL, and everything else 
  - Discussions can be turned into issues if they appear to be issues

If you are unsure whether if issue or question, please choose question (and we can migrate it to issue later)

## Discussion Categories

We will be using GitHub Discussions for Questions and Feature Requests (which have been considered "Issues" in the past) but there a few other categories that can used as well.

![github_categories](https://user-images.githubusercontent.com/11680844/103114878-0ca87400-4626-11eb-9a00-4769f256ab40.png)

Updated Issue Templates
The "New Issue" screen has been updated to the following point_down

![github_issues](https://user-images.githubusercontent.com/11680844/103114905-2b0e6f80-4626-11eb-8df8-e0892bb5930c.png)

There is now only one issue type, Bug reports. Any issues that aren't bug reports will be closed and redirected to Discussions.

Ask a Question and Feature Request will link to Discussions!

__note: if you have added a feature request as an issue in the past & it is still open, I have migrated it & posted the new link in the old issue__

**Comment by Unthred** [comment]
Just installed this and it looks great. Is there any way to move a project from personal into a team project?
